apiVersion: v1 
kind: Pod 
metadata: 
    name: dind-local
    labels:
      app: dind-local
spec: 
    containers: 
      - name: docker-xrdp 
        image: gshiva/azure-ad-xrdp 
        command: ['/usr/bin/supervisord', '-n'] 
        env: 
          - name: DOCKER_HOST 
            value: tcp://localhost:2375
        ports:
          - name: ssh
            containerPort: 22
          - name: xrdp
            containerPort: 3389
      - name: dind-daemon 
        image: docker:17.06.0-dind
        args: [ "--tls=false"]
        securityContext: 
            privileged: true 
        volumeMounts: 
          - name: docker-graph-storage 
            mountPath: /var/lib/docker
      - name: localkube-daemon
        image: gcr.io/k8s-minikube/localkube-dind-image:v1.7.0
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        securityContext:
            privileged: true
        ports:
           - name: api
             containerPort: 8080
    volumes: 
      - name: docker-graph-storage 
        emptyDir: {}
